version: '3.8'

services:
  app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8018
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8018:8018
    restart: unless-stopped
    env_file:
      - ./.env