# Generated by Django 4.2.5 on 2023-09-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_overtimerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
