# Generated by Django 4.2.5 on 2023-09-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_timesheet_hourly_rate_timesheet_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='overtime',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
