# Generated by Django 4.2.5 on 2023-09-25 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timesheet_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='overtime_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.overtimerate'),
        ),
    ]
