# Generated by Django 4.2.5 on 2023-09-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_overtimerate_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='overtime_rate',
        ),
        migrations.DeleteModel(
            name='OvertimeRate',
        ),
    ]
