# Generated by Django 4.2.5 on 2023-09-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_overtime2_timesheet_extra_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='extra_hours',
        ),
    ]
