# Generated by Django 4.2.5 on 2023-09-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_timesheet_end_remove_timesheet_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
