# Generated by Django 4.2.5 on 2023-09-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_duration_timesheet_primary_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
    ]
