# Generated by Django 4.2.5 on 2023-09-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_overtimerate_alter_role_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
