# Generated by Django 4.2.5 on 2023-09-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_timesheet_overtime_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerate',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
