# Generated by Django 4.2.5 on 2023-09-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_timesheet_overtime2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='overtime2',
            new_name='extra_hours',
        ),
    ]
