# Generated by Django 4.2.5 on 2023-09-25 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_timesheet_extra_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='end',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='start',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='end_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
