# Generated by Django 4.2.5 on 2023-09-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_timesheet_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='duration',
            new_name='primary_hours',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='primary_overtime',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='secondary_hours',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='secondary_overtime',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
